repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
      args: [--max-line-length=88]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.660
    hooks:
    - id: mypy
      language_version: python3.7
